from algorithms_tests.DegreeOfSaturationTests import DegreeOfSaturationTests
from algorithms_tests.LargestDegreeOrderingTests import LargestDegreeOrderingTests
from algorithms_tests.RecursivelargestFirstTests import RecursiveLargestFirstTests
from algorithms_tests.EvolutionaryAlgorithmTests import EvolutionaryAlgorithmTests