from repository_tests.StudentsRepositoryTests import StudentRepositoryTests
from repository_tests.TeachersRepositoryTests import TeachersRepositoryTests
from repository_tests.CoursesRepositoryTests import CoursesRepositoryTests