# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\views\new\CreateEntity.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateEntity(object):
    def setupUi(self, CreateEntity):
        CreateEntity.setObjectName("CreateEntity")
        CreateEntity.resize(1034, 356)
        CreateEntity.setStyleSheet("QWidget#CreateEntity {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size:16px;\n"
"    color: red;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel#create_label {\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    height: 35px;\n"
"    width: 100px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    background-color: red;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"    background-color: #EC3812;\n"
"}\n"
"\n"
"QListWidget {\n"
"    margin-top: 8px;\n"
"    border: 1px solid silver;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QListWidget::item::selected {\n"
"    background-color: red;\n"
"    color: white;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(CreateEntity)
        self.verticalLayout.setObjectName("verticalLayout")
        self.create_label = QtWidgets.QLabel(CreateEntity)
        self.create_label.setObjectName("create_label")
        self.verticalLayout.addWidget(self.create_label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.name_label = QtWidgets.QLabel(CreateEntity)
        self.name_label.setObjectName("name_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.name_label)
        self.courses_label = QtWidgets.QLabel(CreateEntity)
        self.courses_label.setObjectName("courses_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.courses_label)
        self.name_input = QtWidgets.QLineEdit(CreateEntity)
        self.name_input.setObjectName("name_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name_input)
        self.courses_list_widget = QtWidgets.QListWidget(CreateEntity)
        self.courses_list_widget.setObjectName("courses_list_widget")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.courses_list_widget)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.save_button = QtWidgets.QPushButton(CreateEntity)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout.addWidget(self.save_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(CreateEntity)
        QtCore.QMetaObject.connectSlotsByName(CreateEntity)

    def retranslateUi(self, CreateEntity):
        _translate = QtCore.QCoreApplication.translate
        CreateEntity.setWindowTitle(_translate("CreateEntity", "Form"))
        self.create_label.setText(_translate("CreateEntity", "Create New Student:"))
        self.name_label.setText(_translate("CreateEntity", "Name:"))
        self.courses_label.setText(_translate("CreateEntity", "Courses:"))
        self.save_button.setText(_translate("CreateEntity", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateEntity = QtWidgets.QWidget()
    ui = Ui_CreateEntity()
    ui.setupUi(CreateEntity)
    CreateEntity.show()
    sys.exit(app.exec_())
