# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\views\assignment\Assignment.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Assignment(object):
    def setupUi(self, Assignment):
        Assignment.setObjectName("Assignment")
        Assignment.resize(730, 412)
        Assignment.setStyleSheet("QWidget#Assignment {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size:16px;\n"
"    color: red;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel#title_label {\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    height: 35px;\n"
"    width: 100px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    background-color: red;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"    background-color: #EC3812;\n"
"}\n"
"\n"
"QListWidget {\n"
"    margin-top: 8px;\n"
"    border: 1px solid silver;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QListWidget::item::selected {\n"
"    background-color: red;\n"
"    color: white;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Assignment)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(Assignment)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.available_course_label = QtWidgets.QLabel(Assignment)
        self.available_course_label.setObjectName("available_course_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.available_course_label)
        self.courses_list_widget = QtWidgets.QListWidget(Assignment)
        self.courses_list_widget.setObjectName("courses_list_widget")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.courses_list_widget)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.save_button = QtWidgets.QPushButton(Assignment)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout.addWidget(self.save_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 113, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(Assignment)
        QtCore.QMetaObject.connectSlotsByName(Assignment)

    def retranslateUi(self, Assignment):
        _translate = QtCore.QCoreApplication.translate
        Assignment.setWindowTitle(_translate("Assignment", "Form"))
        self.title_label.setText(_translate("Assignment", "Assign courses to student Jon Doe:"))
        self.available_course_label.setText(_translate("Assignment", "Available Courses:"))
        self.save_button.setText(_translate("Assignment", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Assignment = QtWidgets.QWidget()
    ui = Ui_Assignment()
    ui.setupUi(Assignment)
    Assignment.show()
    sys.exit(app.exec_())
