# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\views\timetable\Timetable.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Timetable(object):
    def setupUi(self, Timetable):
        Timetable.setObjectName("Timetable")
        Timetable.resize(1075, 562)
        Timetable.setStyleSheet("QWidget#Timetable {\n"
"    background: white;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 18px;\n"
"    color: red;\n"
"    font-weight: bold;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Timetable)
        self.verticalLayout.setObjectName("verticalLayout")
        self.timetable_label = QtWidgets.QLabel(Timetable)
        self.timetable_label.setObjectName("timetable_label")
        self.verticalLayout.addWidget(self.timetable_label)
        self.timetable_widget = QtWidgets.QTableWidget(Timetable)
        self.timetable_widget.setRowCount(12)
        self.timetable_widget.setColumnCount(5)
        self.timetable_widget.setObjectName("timetable_widget")
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.timetable_widget)

        self.retranslateUi(Timetable)
        QtCore.QMetaObject.connectSlotsByName(Timetable)

    def retranslateUi(self, Timetable):
        _translate = QtCore.QCoreApplication.translate
        Timetable.setWindowTitle(_translate("Timetable", "Form"))
        self.timetable_label.setText(_translate("Timetable", "Timetable:"))
        item = self.timetable_widget.verticalHeaderItem(0)
        item.setText(_translate("Timetable", "08:00 - 09:00"))
        item = self.timetable_widget.verticalHeaderItem(1)
        item.setText(_translate("Timetable", "09:00 - 10:00"))
        item = self.timetable_widget.verticalHeaderItem(2)
        item.setText(_translate("Timetable", "10:00 - 11:00"))
        item = self.timetable_widget.verticalHeaderItem(3)
        item.setText(_translate("Timetable", "11:00 - 12:00"))
        item = self.timetable_widget.verticalHeaderItem(4)
        item.setText(_translate("Timetable", "12:00 - 13:00"))
        item = self.timetable_widget.verticalHeaderItem(5)
        item.setText(_translate("Timetable", "13:00 - 14:00"))
        item = self.timetable_widget.verticalHeaderItem(6)
        item.setText(_translate("Timetable", "14:00 - 15:00"))
        item = self.timetable_widget.verticalHeaderItem(7)
        item.setText(_translate("Timetable", "15:00 - 16:00"))
        item = self.timetable_widget.verticalHeaderItem(8)
        item.setText(_translate("Timetable", "16:00 - 17:00"))
        item = self.timetable_widget.verticalHeaderItem(9)
        item.setText(_translate("Timetable", "17:00 - 18:00"))
        item = self.timetable_widget.verticalHeaderItem(10)
        item.setText(_translate("Timetable", "18:00 - 19:00"))
        item = self.timetable_widget.verticalHeaderItem(11)
        item.setText(_translate("Timetable", "19:00 - 20:00"))
        item = self.timetable_widget.horizontalHeaderItem(0)
        item.setText(_translate("Timetable", "Monday"))
        item = self.timetable_widget.horizontalHeaderItem(1)
        item.setText(_translate("Timetable", "Tuesday"))
        item = self.timetable_widget.horizontalHeaderItem(2)
        item.setText(_translate("Timetable", "Wednesday"))
        item = self.timetable_widget.horizontalHeaderItem(3)
        item.setText(_translate("Timetable", "Thursday"))
        item = self.timetable_widget.horizontalHeaderItem(4)
        item.setText(_translate("Timetable", "Friday"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Timetable = QtWidgets.QWidget()
    ui = Ui_Timetable()
    ui.setupUi(Timetable)
    Timetable.show()
    sys.exit(app.exec_())
