# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\views\timetable\Timetable.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Timetable(object):
    def setupUi(self, Timetable):
        Timetable.setObjectName("Timetable")
        Timetable.resize(1158, 537)
        Timetable.setStyleSheet("QWidget#Timetable {\n"
"    background: white;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 18px;\n"
"    color: red;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton {\n"
"    min-height: 50px;\n"
"    width: 150px;\n"
"    font-weight: bold;\n"
"    border-radius: 5px;\n"
"    color: red;\n"
"    background-color:     #D3D3D3;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"    background-color: #DCDCDC;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed, QPushButton[cssClass=\"active\"] {\n"
"    color: white;\n"
"    background-color: red;\n"
"}\n"
"\n"
"QPushButton:pressed:hover, QPushButton[cssClass=\"active\"]:hover {\n"
"    background-color: #EC3812;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    min-width: 200px;\n"
"    min-height: 100px;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Timetable)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.timetable_label = QtWidgets.QLabel(Timetable)
        self.timetable_label.setObjectName("timetable_label")
        self.verticalLayout_2.addWidget(self.timetable_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.students_button = QtWidgets.QPushButton(Timetable)
        self.students_button.setObjectName("students_button")
        self.verticalLayout.addWidget(self.students_button)
        self.teachers_button = QtWidgets.QPushButton(Timetable)
        self.teachers_button.setProperty("cssClass", "")
        self.teachers_button.setObjectName("teachers_button")
        self.verticalLayout.addWidget(self.teachers_button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.list_widget = QtWidgets.QListWidget(Timetable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_widget.sizePolicy().hasHeightForWidth())
        self.list_widget.setSizePolicy(sizePolicy)
        self.list_widget.setObjectName("list_widget")
        self.horizontalLayout.addWidget(self.list_widget)
        self.timetable_widget = QtWidgets.QTableWidget(Timetable)
        self.timetable_widget.setShowGrid(True)
        self.timetable_widget.setRowCount(12)
        self.timetable_widget.setColumnCount(5)
        self.timetable_widget.setObjectName("timetable_widget")
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable_widget.setHorizontalHeaderItem(4, item)
        self.horizontalLayout.addWidget(self.timetable_widget)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Timetable)
        QtCore.QMetaObject.connectSlotsByName(Timetable)

    def retranslateUi(self, Timetable):
        _translate = QtCore.QCoreApplication.translate
        Timetable.setWindowTitle(_translate("Timetable", "Form"))
        self.timetable_label.setText(_translate("Timetable", "Timetable:"))
        self.students_button.setText(_translate("Timetable", "Students"))
        self.students_button.setProperty("cssClass", _translate("Timetable", "active"))
        self.teachers_button.setText(_translate("Timetable", "Teachers"))
        item = self.timetable_widget.verticalHeaderItem(0)
        item.setText(_translate("Timetable", "08:00 - 09:00"))
        item = self.timetable_widget.verticalHeaderItem(1)
        item.setText(_translate("Timetable", "09:00 - 10:00"))
        item = self.timetable_widget.verticalHeaderItem(2)
        item.setText(_translate("Timetable", "10:00 - 11:00"))
        item = self.timetable_widget.verticalHeaderItem(3)
        item.setText(_translate("Timetable", "11:00 - 12:00"))
        item = self.timetable_widget.verticalHeaderItem(4)
        item.setText(_translate("Timetable", "12:00 - 13:00"))
        item = self.timetable_widget.verticalHeaderItem(5)
        item.setText(_translate("Timetable", "13:00 - 14:00"))
        item = self.timetable_widget.verticalHeaderItem(6)
        item.setText(_translate("Timetable", "14:00 - 15:00"))
        item = self.timetable_widget.verticalHeaderItem(7)
        item.setText(_translate("Timetable", "15:00 - 16:00"))
        item = self.timetable_widget.verticalHeaderItem(8)
        item.setText(_translate("Timetable", "16:00 - 17:00"))
        item = self.timetable_widget.verticalHeaderItem(9)
        item.setText(_translate("Timetable", "17:00 - 18:00"))
        item = self.timetable_widget.verticalHeaderItem(10)
        item.setText(_translate("Timetable", "18:00 - 19:00"))
        item = self.timetable_widget.verticalHeaderItem(11)
        item.setText(_translate("Timetable", "19:00 - 20:00"))
        item = self.timetable_widget.horizontalHeaderItem(0)
        item.setText(_translate("Timetable", "Monday"))
        item = self.timetable_widget.horizontalHeaderItem(1)
        item.setText(_translate("Timetable", "Tuesday"))
        item = self.timetable_widget.horizontalHeaderItem(2)
        item.setText(_translate("Timetable", "Wednesday"))
        item = self.timetable_widget.horizontalHeaderItem(3)
        item.setText(_translate("Timetable", "Thursday"))
        item = self.timetable_widget.horizontalHeaderItem(4)
        item.setText(_translate("Timetable", "Friday"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Timetable = QtWidgets.QWidget()
    ui = Ui_Timetable()
    ui.setupUi(Timetable)
    Timetable.show()
    sys.exit(app.exec_())
