from model_tests.StudentTests import StudentTests
from model_tests.TeacherTests import TeacherTests
from model_tests.CourseTests import CourseTests
from model_tests.GraphTests import GraphTests
from model_tests.ChromosomeTests import ChromosomeTests