# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\views\configuration_form\ConfigurationForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfigurationForm(object):
    def setupUi(self, ConfigurationForm):
        ConfigurationForm.setObjectName("ConfigurationForm")
        ConfigurationForm.resize(1031, 450)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ConfigurationForm.sizePolicy().hasHeightForWidth())
        ConfigurationForm.setSizePolicy(sizePolicy)
        ConfigurationForm.setStyleSheet("QWidget#ConfigurationForm {\n"
"    background: white;\n"
"    max-height: 450px;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-weight: bold;\n"
"    font-size: 16px;\n"
"    qproperty-alignment: AlignLeft;\n"
"    margin-left: 2px;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    font: MS Shell Dlg;\n"
"    font-size: 20px;\n"
"    color: red;\n"
"}\n"
"\n"
"QPushButton {\n"
"    max-width: 100px;\n"
"    min-height: 35px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    background-color: red;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"    background-color: #EC3812;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(ConfigurationForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_form_layout = QtWidgets.QFormLayout()
        self.main_form_layout.setObjectName("main_form_layout")
        self.algorithm_label = QtWidgets.QLabel(ConfigurationForm)
        self.algorithm_label.setStyleSheet("")
        self.algorithm_label.setObjectName("algorithm_label")
        self.main_form_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.algorithm_label)
        self.algorithm_combo_box = QtWidgets.QComboBox(ConfigurationForm)
        self.algorithm_combo_box.setObjectName("algorithm_combo_box")
        self.algorithm_combo_box.addItem("")
        self.algorithm_combo_box.addItem("")
        self.algorithm_combo_box.addItem("")
        self.algorithm_combo_box.addItem("")
        self.main_form_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.algorithm_combo_box)
        self.verticalLayout.addLayout(self.main_form_layout)
        self.advanced_group_box = QtWidgets.QGroupBox(ConfigurationForm)
        self.advanced_group_box.setObjectName("advanced_group_box")
        self.formLayout = QtWidgets.QFormLayout(self.advanced_group_box)
        self.formLayout.setObjectName("formLayout")
        self.genrations_label = QtWidgets.QLabel(self.advanced_group_box)
        self.genrations_label.setObjectName("genrations_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.genrations_label)
        self.generations_input = QtWidgets.QLineEdit(self.advanced_group_box)
        self.generations_input.setObjectName("generations_input")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.generations_input)
        self.population_size_label = QtWidgets.QLabel(self.advanced_group_box)
        self.population_size_label.setObjectName("population_size_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.population_size_label)
        self.population_size_input = QtWidgets.QLineEdit(self.advanced_group_box)
        self.population_size_input.setObjectName("population_size_input")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.population_size_input)
        self.mutation_rate_label = QtWidgets.QLabel(self.advanced_group_box)
        self.mutation_rate_label.setObjectName("mutation_rate_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.mutation_rate_label)
        self.mutation_rate_input = QtWidgets.QLineEdit(self.advanced_group_box)
        self.mutation_rate_input.setObjectName("mutation_rate_input")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.mutation_rate_input)
        self.max_daily_break_label = QtWidgets.QLabel(self.advanced_group_box)
        self.max_daily_break_label.setObjectName("max_daily_break_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.max_daily_break_label)
        self.max_daily_break_input = QtWidgets.QLineEdit(self.advanced_group_box)
        self.max_daily_break_input.setObjectName("max_daily_break_input")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.max_daily_break_input)
        self.max_courses_per_day_label = QtWidgets.QLabel(self.advanced_group_box)
        self.max_courses_per_day_label.setObjectName("max_courses_per_day_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.max_courses_per_day_label)
        self.max_courses_per_day_input = QtWidgets.QLineEdit(self.advanced_group_box)
        self.max_courses_per_day_input.setObjectName("max_courses_per_day_input")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.max_courses_per_day_input)
        self.verticalLayout.addWidget(self.advanced_group_box)
        self.penalties_group_box = QtWidgets.QGroupBox(ConfigurationForm)
        self.penalties_group_box.setObjectName("penalties_group_box")
        self.formLayout_2 = QtWidgets.QFormLayout(self.penalties_group_box)
        self.formLayout_2.setObjectName("formLayout_2")
        self.invalid_solution_label = QtWidgets.QLabel(self.penalties_group_box)
        self.invalid_solution_label.setObjectName("invalid_solution_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.invalid_solution_label)
        self.invalid_solution_input = QtWidgets.QLineEdit(self.penalties_group_box)
        self.invalid_solution_input.setObjectName("invalid_solution_input")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.invalid_solution_input)
        self.overcrowding_label = QtWidgets.QLabel(self.penalties_group_box)
        self.overcrowding_label.setObjectName("overcrowding_label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.overcrowding_label)
        self.overcrowding_input = QtWidgets.QLineEdit(self.penalties_group_box)
        self.overcrowding_input.setObjectName("overcrowding_input")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.overcrowding_input)
        self.fragmentation_label = QtWidgets.QLabel(self.penalties_group_box)
        self.fragmentation_label.setObjectName("fragmentation_label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.fragmentation_label)
        self.fragmentation_input = QtWidgets.QLineEdit(self.penalties_group_box)
        self.fragmentation_input.setObjectName("fragmentation_input")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fragmentation_input)
        self.uniformity_label = QtWidgets.QLabel(self.penalties_group_box)
        self.uniformity_label.setObjectName("uniformity_label")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.uniformity_label)
        self.uniformity_input = QtWidgets.QLineEdit(self.penalties_group_box)
        self.uniformity_input.setObjectName("uniformity_input")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.uniformity_input)
        self.verticalLayout.addWidget(self.penalties_group_box)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.submit_button = QtWidgets.QPushButton(ConfigurationForm)
        self.submit_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.submit_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.submit_button.setObjectName("submit_button")
        self.horizontalLayout_2.addWidget(self.submit_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(ConfigurationForm)
        QtCore.QMetaObject.connectSlotsByName(ConfigurationForm)

    def retranslateUi(self, ConfigurationForm):
        _translate = QtCore.QCoreApplication.translate
        ConfigurationForm.setWindowTitle(_translate("ConfigurationForm", "Form"))
        self.algorithm_label.setText(_translate("ConfigurationForm", "Algorithm:"))
        self.algorithm_combo_box.setItemText(0, _translate("ConfigurationForm", "Largest Degree Ordering Algorithm"))
        self.algorithm_combo_box.setItemText(1, _translate("ConfigurationForm", "Degree Of Saturation Algorithm"))
        self.algorithm_combo_box.setItemText(2, _translate("ConfigurationForm", "Recursive Largest First Algorithm"))
        self.algorithm_combo_box.setItemText(3, _translate("ConfigurationForm", "Evolutionary Algorithm"))
        self.advanced_group_box.setTitle(_translate("ConfigurationForm", "Advanced"))
        self.genrations_label.setText(_translate("ConfigurationForm", "Generations:"))
        self.generations_input.setText(_translate("ConfigurationForm", "100"))
        self.population_size_label.setText(_translate("ConfigurationForm", "Population Size:"))
        self.population_size_input.setText(_translate("ConfigurationForm", "100"))
        self.mutation_rate_label.setText(_translate("ConfigurationForm", "Mutation Probability:"))
        self.mutation_rate_input.setText(_translate("ConfigurationForm", "60"))
        self.max_daily_break_label.setText(_translate("ConfigurationForm", "Max Daily Break:"))
        self.max_daily_break_input.setText(_translate("ConfigurationForm", "2"))
        self.max_courses_per_day_label.setText(_translate("ConfigurationForm", "Max Daily Courses: "))
        self.max_courses_per_day_input.setText(_translate("ConfigurationForm", "6"))
        self.penalties_group_box.setTitle(_translate("ConfigurationForm", "Penalties"))
        self.invalid_solution_label.setText(_translate("ConfigurationForm", "Invalid Solution Penalty:"))
        self.invalid_solution_input.setText(_translate("ConfigurationForm", "1024"))
        self.overcrowding_label.setText(_translate("ConfigurationForm", "Overcrowding Penalty:"))
        self.overcrowding_input.setText(_translate("ConfigurationForm", "64"))
        self.fragmentation_label.setText(_translate("ConfigurationForm", "Fragmentation Penalty:"))
        self.fragmentation_input.setText(_translate("ConfigurationForm", "32"))
        self.uniformity_label.setText(_translate("ConfigurationForm", "Uniformity Penalty:"))
        self.uniformity_input.setText(_translate("ConfigurationForm", "16"))
        self.submit_button.setText(_translate("ConfigurationForm", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ConfigurationForm = QtWidgets.QWidget()
    ui = Ui_ConfigurationForm()
    ui.setupUi(ConfigurationForm)
    ConfigurationForm.show()
    sys.exit(app.exec_())
