# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\views\simulator\Simulator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Simulator(object):
    def setupUi(self, Simulator):
        Simulator.setObjectName("Simulator")
        Simulator.resize(1183, 772)
        Simulator.setStyleSheet("QWidget#centralwidget {\n"
"    background-color: white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Simulator)
        self.centralwidget.setObjectName("centralwidget")
        self.students_label = QtWidgets.QLabel(self.centralwidget)
        self.students_label.setGeometry(QtCore.QRect(10, 150, 101, 21))
        self.students_label.setStyleSheet("QLabel {\n"
"    color: red;\n"
"    font-weight: bold;\n"
"    font-size: 18px;\n"
"    qproperty-alignment: AlignLeft;\n"
"    margin-bottom: 2px;\n"
"}")
        self.students_label.setAlignment(QtCore.Qt.AlignLeading)
        self.students_label.setObjectName("students_label")
        self.teachers_label = QtWidgets.QLabel(self.centralwidget)
        self.teachers_label.setGeometry(QtCore.QRect(10, 400, 101, 21))
        self.teachers_label.setStyleSheet("QLabel {\n"
"    color: red;\n"
"    font-weight: bold;\n"
"    font-size: 18px;\n"
"    qproperty-alignment: AlignLeft;\n"
"    margin-bottom: 2px;\n"
"}")
        self.teachers_label.setAlignment(QtCore.Qt.AlignLeading)
        self.teachers_label.setObjectName("teachers_label")
        self.students_list_widget = QtWidgets.QListWidget(self.centralwidget)
        self.students_list_widget.setGeometry(QtCore.QRect(10, 170, 571, 221))
        self.students_list_widget.setObjectName("students_list_widget")
        self.teachers_list_widget = QtWidgets.QListWidget(self.centralwidget)
        self.teachers_list_widget.setGeometry(QtCore.QRect(10, 420, 571, 221))
        self.teachers_list_widget.setObjectName("teachers_list_widget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1181, 127))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo_image = QtWidgets.QLabel(self.widget)
        self.logo_image.setMaximumSize(QtCore.QSize(150, 125))
        self.logo_image.setText("")
        self.logo_image.setPixmap(QtGui.QPixmap(".\\src\\views\\simulator\\../../../assets/klc_logo.svg"))
        self.logo_image.setScaledContents(True)
        self.logo_image.setObjectName("logo_image")
        self.horizontalLayout.addWidget(self.logo_image)
        self.title_label = QtWidgets.QLabel(self.widget)
        self.title_label.setStyleSheet("QLabel {\n"
"    font-size: 35px;\n"
"    font-weight: bold;\n"
"    color: red;\n"
"    max-height: 100px;\n"
"}")
        self.title_label.setScaledContents(False)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.horizontalLayout.addWidget(self.title_label)
        Simulator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Simulator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1183, 26))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menuRun = QtWidgets.QMenu(self.menubar)
        self.menuRun.setObjectName("menuRun")
        Simulator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Simulator)
        self.statusbar.setObjectName("statusbar")
        Simulator.setStatusBar(self.statusbar)
        self.actionChange_Dataset = QtWidgets.QAction(Simulator)
        self.actionChange_Dataset.setObjectName("actionChange_Dataset")
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionChange_Dataset)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())

        self.retranslateUi(Simulator)
        QtCore.QMetaObject.connectSlotsByName(Simulator)

    def retranslateUi(self, Simulator):
        _translate = QtCore.QCoreApplication.translate
        Simulator.setWindowTitle(_translate("Simulator", "University Timetabling Simulator"))
        self.students_label.setText(_translate("Simulator", "Students:"))
        self.teachers_label.setText(_translate("Simulator", "Teachers:"))
        self.title_label.setText(_translate("Simulator", "University Timetabling Simulator"))
        self.menu_File.setTitle(_translate("Simulator", "&File"))
        self.menuRun.setTitle(_translate("Simulator", "Run"))
        self.actionChange_Dataset.setText(_translate("Simulator", "Change Dataset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Simulator = QtWidgets.QMainWindow()
    ui = Ui_Simulator()
    ui.setupUi(Simulator)
    Simulator.show()
    sys.exit(app.exec_())
